# This is a basic workflow to help you get started with Actions

name: Build jme-alloc

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
    compile-java:
      # runner images with architectures (variants)
      runs-on: ${{ matrix.os }}
      strategy:
        matrix:
          os: [ 'ubuntu-latest' ]
          java: ['17']
          architecture: [ 'x64' ]
      name: Compile java 

      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
        - uses: actions/checkout@v3

        - name: Compiling native code into a shared object file
          run: ./gradlew :jme3-alloc:compileJava

        - name: Archive byte code 
          uses: actions/upload-artifact@v3
          with:
            name: byte-code
            path: jme3-alloc/build/classes/java/main/

        - name: Archive jni headers
          uses: actions/upload-artifact@v3
          with:
            name: jni-headers
            path: jme3-alloc-native/src/include/

    compile-natives:
        # runner images with architectures (variants)
        runs-on: ${{ matrix.os }}
        needs: compile-java
        strategy:
          matrix:
            os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
            architecture: [ 'x64' ]
        name: Compile natives on ${{ matrix.os }} for x86-64 and x86

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          - uses: actions/checkout@v3

          - name: Download jni headers
            uses: actions/download-artifact@v3
            with:
              name: jni-headers
              path: jme3-alloc-native/src/include/

          - name: Compiling x86-64 on ${{ matrix.os }}
            run: ./gradlew :jme3-alloc-native:build 
          
          - name: Compiling x86 on ${{ matrix.os }}
            run: ./gradlew :jme3-alloc-native:compileX86
          
          - name: Archive libjmealloc.so
            uses: actions/upload-artifact@v3
            with:
              name: libjmealloc-${{ matrix.os }}
              path: jme3-alloc-native/build/
    assemble:
        # runner images with architectures (variants)
        runs-on: ${{ matrix.os }}
        needs: compile-natives
        strategy:
          matrix:
            os: [ 'ubuntu-latest' ]
            java: ['17']
            architecture: [ 'x64' ]
        name: Assemble jme-alloc

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          - uses: actions/checkout@v3

          - name: Downloading libjmealloc-ubuntu-latest
            uses: actions/download-artifact@v3
            with:
              name: libjmealloc-ubuntu-latest
              path: jme3-alloc-native/build/

          - name: Downloading libjmealloc-macos-latest
            uses: actions/download-artifact@v3
            with:
              name: libjmealloc-macos-latest
              path: jme3-alloc-native/build/

          - name: Downloading libjmealloc-windows-latest
            uses: actions/download-artifact@v3
            with:
              name: libjmealloc-windows-latest
              path: jme3-alloc-native/build/

          - name: Downloading byte code
            uses: actions/download-artifact@v3
            with:
              name: byte-code
              path: jme3-alloc/build/classes/java/main/
            
          - name: Copying natives
            run: ./gradlew :jme3-alloc-native:copyNatives
            
          - name: List build
            run: tree jme3-alloc/build/classes/java/main/

          - name: Assemble 
            run: ./gradlew :jme3-alloc:assemble

          - name: Log jar
            run: tree jme3-alloc/build/libs/
          
          - name: Archive release
            uses: actions/upload-artifact@v3
            with:
              name: release-archive
              path: jme3-alloc/build/libs/*.jar
