# This is a basic workflow to help you get started with Actions

name: Build jme-alloc

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  compile-natives:
    # runner images with architectures (variants)
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ 'ubuntu-latest', 'macos-latest', 'windows-latest' ]
        architecture: [ 'x64', 'x86' ]
    name: Compile natives on ${{ matrix.os }}_${{ matrix.architecture }}
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3

      - name: Compiling native code into a shared object file
        run: ./gradlew :native-alloc:build
        
      - name: Archive libjmealloc.so
        uses: actions/upload-artifact@v3
        with:
          name: libjmealloc-${{ matrix.os }}_${{ matrix.architecture }}
          path: ./native-alloc/build/
